DATASET: 'ROAD'
MODE: 'train'

PRIDECTION:
  OBS_TIME: 1 
  PRED_TIME: 1
  OVERLAP: 0

TRAIN:
  DEVICE: 0,1,2,3,4,5,6,7 # -1 for cpu
  BATCH_SIZE: 32
  NUM_WORKERS: 4
  NUM_EPOCH: 50
  LR: 1e-4
  MIN_LR: 1e-5
  LR_BACKBONE: 1e-5
  MOMENTUM: 0.9
  W_DECAY: 1e-4
  LR_POLICY: 'step'
  USE_WARMUP: True
  WARMUP_START_LR: 1e-5
  WARMUP_EPOCHS: 4
  LR_MILESTONE: [10, 15]
  STEP: 0.1
  SEED: 1
  OPTIMIZER:
    NAME: SGD
  AUX_LOSS: True

VAL:
  BATCH_SIZE: 1
  FREQ: 2

DATA:
  DATASET_NAME: 'ROAD'
  DATA_PATH: '../road-dataset/road'
  INPUT: 'FEATURES' # 'FRAMES' or 'FEATURES'
  TRAIN_ANNO: 'road_trainval_v1.0.json'
  TEST_ANNO: 'road_test_v1.0.json'
  TRAIN_SUBSETS: 'train_3'
  VAL_SUBSETS: 'val_3'
  TEST_SUBSETS: 'test'
  NUM_CLASSES: 80
  IMG_RESHAPE_SIZE: 224
  TEMP_LEN: 32
  FREQUENCY: 12
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]

MODEL:
  SINGLE_FRAME: True
  BACKBONE_NAME: CSN-152
  TEMPORAL_DS_STRATEGY: avg
  LAST_STRIDE: False
  GENERATE_LFB: False
  NAME: 'ava_detr_9_224'
  ENC_LAYERS: 6
  DEC_LAYERS: 6
  D_MODEL: 256
  NHEAD: 8
  NUM_ENCODER_LAYERS: 12
  DIM_FEEDFORWARD: 2048
  QUERY_NUM: 15
  NORMALIZE_BEFORE: False
  DROPOUT: 0.1
  DS_RATE: 8
  TEMP_LEN: 32
  SAMPLE_RATE: 2
  PRETRAINED: False
  PRETRAIN_BACKBONE_DIR: "/xxx/irCSN_152_ft_kinetics_from_ig65m_f126851907.mat"
  PRETRAIN_TRANSFORMER_DIR: "/xxx/detr.pth"
  PRETRAINED_PATH: "/xxx/ADTR_CSN_152_ava_21.pth"
  LOAD: True
  LOAD_FC: True

LOSS_COFS:
  MASK_COF: 1
  DICE_COF: 12
  BBOX_COF: 5
  GIOU_COF: 2
  EOS_COF: 0.1
  WEIGHT: 10
  WEIGHT_CHANGE: 1000
  LOSS_CHANGE_COF: 2
  CLIPS_MAX_NORM: 0.1

LOG:
  BASE_PATH: '/xxx/AVA_Tuber'
  LOG_DIR: 'tb_log'
  SAVE_DIR: 'checkpoints'
  EVAL_DIR: '/xxx/AVA_Tuber/eval'
  SAVE_FREQ: 1
  RES_DIR: 'tmp2'